# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_salary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_base_salary_window(object):
    def setupUi(self, base_salary_window):
        base_salary_window.setObjectName("base_salary_window")
        base_salary_window.resize(591, 270)
        self.dep_list = QtWidgets.QListWidget(base_salary_window)
        self.dep_list.setGeometry(QtCore.QRect(70, 50, 111, 192))
        self.dep_list.setObjectName("dep_list")
        self.staff_list = QtWidgets.QListWidget(base_salary_window)
        self.staff_list.setGeometry(QtCore.QRect(260, 50, 161, 192))
        self.staff_list.setObjectName("staff_list")
        self.label = QtWidgets.QLabel(base_salary_window)
        self.label.setGeometry(QtCore.QRect(20, 60, 41, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(base_salary_window)
        self.label_2.setGeometry(QtCore.QRect(220, 60, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(base_salary_window)
        self.label_3.setGeometry(QtCore.QRect(440, 60, 101, 16))
        self.label_3.setObjectName("label_3")
        self.new_base_salary = QtWidgets.QLineEdit(base_salary_window)
        self.new_base_salary.setGeometry(QtCore.QRect(430, 130, 113, 20))
        self.new_base_salary.setObjectName("new_base_salary")
        self.change_button = QtWidgets.QPushButton(base_salary_window)
        self.change_button.setGeometry(QtCore.QRect(440, 180, 75, 23))
        self.change_button.setObjectName("change_button")
        self.label_4 = QtWidgets.QLabel(base_salary_window)
        self.label_4.setGeometry(QtCore.QRect(440, 110, 101, 16))
        self.label_4.setObjectName("label_4")
        self.base_salary = QtWidgets.QLabel(base_salary_window)
        self.base_salary.setGeometry(QtCore.QRect(440, 80, 101, 16))
        self.base_salary.setText("")
        self.base_salary.setObjectName("base_salary")

        self.retranslateUi(base_salary_window)
        QtCore.QMetaObject.connectSlotsByName(base_salary_window)

    def retranslateUi(self, base_salary_window):
        _translate = QtCore.QCoreApplication.translate
        base_salary_window.setWindowTitle(_translate("base_salary_window", "修改基本工资"))
        self.label.setText(_translate("base_salary_window", "部门："))
        self.label_2.setText(_translate("base_salary_window", "姓名："))
        self.label_3.setText(_translate("base_salary_window", "基本工资为："))
        self.change_button.setText(_translate("base_salary_window", "修改"))
        self.label_4.setText(_translate("base_salary_window", "修改为："))
