# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bonous.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bonous_window(object):
    def setupUi(self, bonous_window):
        bonous_window.setObjectName("bonous_window")
        bonous_window.resize(783, 435)
        self.bonoustable = QtWidgets.QTableView(bonous_window)
        self.bonoustable.setGeometry(QtCore.QRect(40, 50, 617, 331))
        self.bonoustable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.bonoustable.setObjectName("bonoustable")
        self.addbutton = QtWidgets.QPushButton(bonous_window)
        self.addbutton.setGeometry(QtCore.QRect(690, 120, 75, 23))
        self.addbutton.setObjectName("addbutton")
        self.delbutthon = QtWidgets.QPushButton(bonous_window)
        self.delbutthon.setGeometry(QtCore.QRect(690, 170, 75, 23))
        self.delbutthon.setObjectName("delbutthon")
        self.changebutton = QtWidgets.QPushButton(bonous_window)
        self.changebutton.setGeometry(QtCore.QRect(690, 230, 75, 23))
        self.changebutton.setObjectName("changebutton")

        self.retranslateUi(bonous_window)
        QtCore.QMetaObject.connectSlotsByName(bonous_window)

    def retranslateUi(self, bonous_window):
        _translate = QtCore.QCoreApplication.translate
        bonous_window.setWindowTitle(_translate("bonous_window", "修改奖金"))
        self.addbutton.setText(_translate("bonous_window", "增加一行"))
        self.delbutthon.setText(_translate("bonous_window", "删除该行"))
        self.changebutton.setText(_translate("bonous_window", "提交修改"))
