# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(249, 261)
        self.account = QtWidgets.QLineEdit(login_window)
        self.account.setGeometry(QtCore.QRect(70, 60, 113, 20))
        self.account.setObjectName("account")
        self.label_account = QtWidgets.QLabel(login_window)
        self.label_account.setGeometry(QtCore.QRect(70, 30, 111, 16))
        self.label_account.setObjectName("label_account")
        self.label_password = QtWidgets.QLabel(login_window)
        self.label_password.setGeometry(QtCore.QRect(70, 100, 111, 16))
        self.label_password.setObjectName("label_password")
        self.password = QtWidgets.QLineEdit(login_window)
        self.password.setGeometry(QtCore.QRect(70, 130, 113, 20))
        self.password.setObjectName("password")
        self.login_button = QtWidgets.QPushButton(login_window)
        self.login_button.setGeometry(QtCore.QRect(70, 190, 111, 23))
        self.login_button.setObjectName("login_button")
        self.radioButton = QtWidgets.QRadioButton(login_window)
        self.radioButton.setGeometry(QtCore.QRect(80, 160, 89, 16))
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "登录"))
        self.label_account.setText(_translate("login_window", "员工号："))
        self.label_password.setText(_translate("login_window", "密码："))
        self.login_button.setText(_translate("login_window", "登录"))
        self.radioButton.setText(_translate("login_window", "管理员登录"))
