# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffsalary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_staff_salary_window(object):
    def setupUi(self, staff_salary_window):
        staff_salary_window.setObjectName("staff_salary_window")
        staff_salary_window.resize(906, 514)
        self.staffsalarytable = QtWidgets.QTableView(staff_salary_window)
        self.staffsalarytable.setGeometry(QtCore.QRect(0, 0, 911, 521))
        self.staffsalarytable.setMouseTracking(False)
        self.staffsalarytable.setObjectName("staffsalarytable")

        self.retranslateUi(staff_salary_window)
        QtCore.QMetaObject.connectSlotsByName(staff_salary_window)

    def retranslateUi(self, staff_salary_window):
        _translate = QtCore.QCoreApplication.translate
        staff_salary_window.setWindowTitle(_translate("staff_salary_window", "个人工资流水"))
