# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_password(object):
    def setupUi(self, update_password):
        update_password.setObjectName("update_password")
        update_password.resize(319, 152)
        self.submit_button = QtWidgets.QPushButton(update_password)
        self.submit_button.setGeometry(QtCore.QRect(110, 120, 111, 23))
        self.submit_button.setObjectName("submit_button")
        self.widget = QtWidgets.QWidget(update_password)
        self.widget.setGeometry(QtCore.QRect(40, 30, 211, 81))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.old_password = QtWidgets.QLineEdit(self.widget)
        self.old_password.setObjectName("old_password")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.old_password)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.new_password = QtWidgets.QLineEdit(self.widget)
        self.new_password.setObjectName("new_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.new_password)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.re_new_password = QtWidgets.QLineEdit(self.widget)
        self.re_new_password.setObjectName("re_new_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.re_new_password)

        self.retranslateUi(update_password)
        QtCore.QMetaObject.connectSlotsByName(update_password)

    def retranslateUi(self, update_password):
        _translate = QtCore.QCoreApplication.translate
        update_password.setWindowTitle(_translate("update_password", "修改密码"))
        self.submit_button.setText(_translate("update_password", "确认修改"))
        self.label.setText(_translate("update_password", "原密码"))
        self.label_2.setText(_translate("update_password", "新密码"))
        self.label_3.setText(_translate("update_password", "确认新密码"))
